package Telas;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import classesExec.ClienteSocket;



public class Arquivos extends classesExec.MudaTema {
    // Variaveis
    int idSelecionado;
    ClienteSocket client;
    protected static ClienteScreen cli = null;
    String[] arquivosNoServidor;
    /**
     * Creates new form Arquivos
     * @param id
     * @param clienteSocket
     * Construtor da classe que recupera o id do cliente e o clienteSocket da classe ClienteScreen
     */
    public Arquivos(int id, ClienteSocket clienteSocket, ClienteScreen cliente) {
        initComponents();
        this.idSelecionado = id;
        this.client = clienteSocket;
        this.listArquivos.setListData(client.recuperaArquivosNoServidor());
        this.cli = cliente;
        this.mudaCor();
        
        this.setLocationRelativeTo(null);
    }
    
    @Override
    protected void mudaCor(){
        if(cli.pegaCor()){
            panelBaixar.setBackground(escuro);
            panelEnviar.setBackground(escuro);
            jPanel1.setBackground(escuro);
            btnAtualizar.setBackground(botao_escuro);
            btnAtualizar.setForeground(text_escuro);
            btnBaixar.setBackground(botao_escuro);
            btnBaixar.setForeground(text_escuro);
            btnEnviar.setBackground(botao_escuro);
            btnEnviar.setForeground(text_escuro);
            btnSelecionar.setBackground(botao_escuro);
            btnSelecionar.setForeground(text_escuro);
            lblCaminho.setForeground(text_claro);
            listArquivos.setBackground(area_escuro);
            listArquivos.setForeground(text_claro);
            txtCaminho.setBackground(area_escuro);
            txtCaminho.setForeground(text_claro);
            
        }else{
            panelBaixar.setBackground(claro);
            panelEnviar.setBackground(claro);
            jPanel1.setBackground(claro);
            btnAtualizar.setBackground(botao_claro);
            btnAtualizar.setForeground(text_claro);
            btnBaixar.setBackground(botao_claro);
            btnBaixar.setForeground(text_claro);
            btnEnviar.setBackground(botao_claro);
            btnEnviar.setForeground(text_claro);
            btnSelecionar.setBackground(botao_claro);
            btnSelecionar.setForeground(text_claro);
            lblCaminho.setForeground(text_escuro);
            listArquivos.setBackground(area_claro);
            listArquivos.setForeground(text_escuro);
            txtCaminho.setBackground(area_claro);
            txtCaminho.setForeground(text_escuro);
        }
    }

    private Arquivos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPanel_Principal = new javax.swing.JTabbedPane();
        panelBaixar = new javax.swing.JPanel();
        btnBaixar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listArquivos = new javax.swing.JList<>();
        btnAtualizar = new javax.swing.JButton();
        panelEnviar = new javax.swing.JPanel();
        lblCaminho = new javax.swing.JLabel();
        txtCaminho = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        panelVisualizar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblVisualizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionador de arquivos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnBaixar.setText("BAIXAR");
        btnBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixarActionPerformed(evt);
            }
        });

        listArquivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listArquivos);

        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBaixarLayout = new javax.swing.GroupLayout(panelBaixar);
        panelBaixar.setLayout(panelBaixarLayout);
        panelBaixarLayout.setHorizontalGroup(
            panelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaixarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelBaixarLayout.createSequentialGroup()
                        .addGap(0, 188, Short.MAX_VALUE)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBaixarLayout.setVerticalGroup(
            panelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBaixarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaixar)
                    .addComponent(btnAtualizar))
                .addContainerGap())
        );

        tabbedPanel_Principal.addTab("Baixar", panelBaixar);

        lblCaminho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCaminho.setText("Caminho:");

        txtCaminho.setEditable(false);
        txtCaminho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnSelecionar.setText("SELECIONAR");
        btnSelecionar.setToolTipText("");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVisualizar.setText("<visualizar>");
        jScrollPane2.setViewportView(lblVisualizar);

        javax.swing.GroupLayout panelVisualizarLayout = new javax.swing.GroupLayout(panelVisualizar);
        panelVisualizar.setLayout(panelVisualizarLayout);
        panelVisualizarLayout.setHorizontalGroup(
            panelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelVisualizarLayout.setVerticalGroup(
            panelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEnviarLayout = new javax.swing.GroupLayout(panelEnviar);
        panelEnviar.setLayout(panelEnviarLayout);
        panelEnviarLayout.setHorizontalGroup(
            panelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEnviarLayout.createSequentialGroup()
                        .addComponent(lblCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCaminho, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnviarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelEnviarLayout.setVerticalGroup(
            panelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaminho)
                    .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnSelecionar))
                .addContainerGap())
        );

        tabbedPanel_Principal.addTab("Enviar", panelEnviar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbedPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // Atualiza a lista de arquivos no servidor
        this.arquivosNoServidor = client.recuperaArquivosNoServidor();

        this.listArquivos.setListData(arquivosNoServidor);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixarActionPerformed
        //Abre um JFileChooser para o usuário escolher onde quer salvar o arquivo
        String pathFinal = escolherLocalParaSalvarArquivo();

        //String que pega o nome do arquivo selecionado no JList e monta o caminho do arquivo no servidor
        String caminho = "./tempServer/" + listArquivos.getSelectedValue().toString();

        //Verifica se o caminho é valido e faz o download do arquivo
        if (pathFinal != null && !pathFinal.trim().isEmpty()) {
            client.baixarArquivo(caminho, pathFinal);
        }
    }//GEN-LAST:event_btnBaixarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // Botão que tranfere o arquivo para o servidor
        if(!txtCaminho.getText().isEmpty()){
            client.transferirArquivo(idSelecionado, file);
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum arquivo selecionado", "Erro ao transferir arquivo.", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        // Botão que abre um JFileChooser para o usuário escolher o arquivo a ser enviado
        JFileChooser fileChooser = new JFileChooser();
        int option = fileChooser.showDialog(null, "Selecionar");

        // Verifica se o usuário escolheu um arquivo e se o mesmo é válido
        try{
            if (option == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile(); //Arquivo selecionado pelo usário
                txtCaminho.setText(file.getAbsolutePath());
                long fileLength = file.length();
                if (fileLength > Integer.MAX_VALUE)
                JOptionPane.showMessageDialog(null, "Arquivo muito grande, não é possível transferi-lo.", "Erro ao transferir arquivo.", JOptionPane.ERROR_MESSAGE);
                else if (!file.isFile())
                JOptionPane.showMessageDialog(null, "A seleção não é um arquivo.", "Erro ao transferir arquivo.", JOptionPane.ERROR_MESSAGE);

                File fileVerificar = file;
                lblVisualizar.setText("");
                if (getFileExtension(fileVerificar.getName()).equalsIgnoreCase("txt")) {
                    lblVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/txt-icon.png")));
                } else if (getFileExtension(fileVerificar.getName()).equalsIgnoreCase("png") || getFileExtension(fileVerificar.getName()).equalsIgnoreCase("jpeg") || getFileExtension(fileVerificar.getName()).equalsIgnoreCase("jpg")) {
                    lblVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/img-icon.png")));
                } else {
                    lblVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/file-icon.png")));
                }
            }
        }catch(Exception ex){
            System.out.println("");
        }

    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        arqui = null;
    }//GEN-LAST:event_formWindowClosing

    
    File file;    
    private String getFileExtension(String fileName) {
        //Recupera a extensão do arquivo
        int i  = fileName.lastIndexOf('.');
        
        if (i > 0) {
            return fileName.substring(i + 1);
        } else {
            return "";
        }   
    }    
    public String escolherLocalParaSalvarArquivo() {
        //Abre JFileChooser para escolher o lugar para salver o arquivo
        JFileChooser fileChooser = new JFileChooser(); 
        fileChooser.setCurrentDirectory(new java.io.File("."));
        fileChooser.setDialogTitle("Escolha o diretório para salvar");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
            return fileChooser.getSelectedFile().toString();
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arquivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arquivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBaixar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCaminho;
    private javax.swing.JLabel lblVisualizar;
    private javax.swing.JList<String> listArquivos;
    private javax.swing.JPanel panelBaixar;
    private javax.swing.JPanel panelEnviar;
    private javax.swing.JPanel panelVisualizar;
    private javax.swing.JTabbedPane tabbedPanel_Principal;
    private javax.swing.JTextField txtCaminho;
    // End of variables declaration//GEN-END:variables
}
