package Telas;


import classesExec.InformacoesCliente;
import static Telas.Cadastra_Host.validIP;
import java.awt.Point;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.MalformedURLException;
import java.net.Socket;
import java.net.URL;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;



public class Cadastra_Cliente extends classesExec.MudaTema {
    //Atributo da calsse
    String ipLocal, ipPublico;
    private Point pcliente;

    //Construtor da classe
    public Cadastra_Cliente() {
        initComponents();
        ipLocal = getIPLocal();
        ipPublico = getIPPublico();
        this.mudaCor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldIpPublicoServidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIpPublicoCliente = new javax.swing.JTextField();
        jTextFieldIpLocalServidor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextFieldIpLocalCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBoxCliente = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Cadastra Cliente");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jTextFieldNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldIpPublicoServidor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldIpPublicoServidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("IP Público do servidor:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("IP Local do servidor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Seu IP Público:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Seu IP Local:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Nome de chat: ");

        jTextFieldIpPublicoCliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldIpPublicoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldIpLocalServidor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldIpLocalServidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/LogoLovelace-1.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(31, 135, 235));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setText("VOLTAR");
        jButton2.setToolTipText("");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldIpLocalCliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextFieldIpLocalCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton1.setBackground(new java.awt.Color(31, 135, 235));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("CONECTAR");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxCliente.setBackground(new java.awt.Color(255, 204, 102));
        jCheckBoxCliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jCheckBoxCliente.setText("Preencher automático");
        jCheckBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxClienteActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 102));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/LampadaIcon30x30Preto.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIpPublicoServidor)
                                    .addComponent(jTextFieldIpLocalServidor)
                                    .addComponent(jTextFieldIpPublicoCliente)
                                    .addComponent(jTextFieldIpLocalCliente)
                                    .addComponent(jTextFieldNome))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIpPublicoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldIpLocalServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldIpPublicoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIpLocalCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Classe sobrescrita para mudar cor. Seta as cores em todos os componentes
    @Override
    protected void mudaCor(){
        if(getCor()){
            jButton1.setBackground(botao_escuro);
            jButton1.setForeground(text_escuro);
            jButton2.setBackground(botao_escuro);
            jButton2.setForeground(text_escuro);
            jButton3.setBackground(escuro);
            jLabel3.setForeground(text_claro);
            jLabel4.setForeground(text_claro);
            jLabel5.setForeground(text_claro);
            jLabel6.setForeground(text_claro);
            jLabel7.setForeground(text_claro);
            jPanel1.setBackground(escuro);
            jCheckBoxCliente.setForeground(text_claro);
            jCheckBoxCliente.setBackground(escuro);
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/LampadaIcon30x30Branco.png")));
            jButton3.setBackground(escuro);
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/PretoInicial.png")));

        }else{
            jButton1.setBackground(botao_claro);
            jButton1.setForeground(text_claro);
            jButton2.setBackground(botao_claro);
            jButton2.setForeground(text_claro);
            jButton3.setBackground(claro);
            jLabel3.setForeground(text_escuro);
            jLabel4.setForeground(text_escuro);
            jLabel5.setForeground(text_escuro);
            jLabel6.setForeground(text_escuro);
            jLabel7.setForeground(text_escuro);
            jPanel1.setBackground(claro);
            jCheckBoxCliente.setForeground(text_escuro);
            jCheckBoxCliente.setBackground(claro);
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/LampadaIcon30x30Preto.png")));
            jButton3.setBackground(claro);
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotos/BrancoInicial2.png")));
        }
    }
    
    private Point getPosicao(){
        Point p = this.getLocation();
        return p;
    }
    
    private void jCheckBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxClienteActionPerformed
        
        //Pega o valor do IP público e local e preenche automaticamente os campos
        if (jCheckBoxCliente.isSelected()) {
            jTextFieldIpPublicoCliente.setText(ipPublico);
            jTextFieldIpPublicoCliente.setEnabled(false);
            jTextFieldIpLocalCliente.setText(ipLocal);
            jTextFieldIpLocalCliente.setEnabled(false);

        //Else habilita os campos para serem preenchidos pelo usuário
        }else{
            jTextFieldIpPublicoCliente.setText("");
            jTextFieldIpPublicoCliente.setEnabled(true);
            jTextFieldIpLocalCliente.setText("");
            jTextFieldIpLocalCliente.setEnabled(true);
        } 
            
    }//GEN-LAST:event_jCheckBoxClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Verifica se os IPs estão corretos e conecta com o servidor caso estejam
        if (isValidLogin()) {
        InformacoesCliente infoCliente = new InformacoesCliente(0, jTextFieldIpPublicoCliente.getText(), jTextFieldIpLocalCliente.getText(), jTextFieldNome.getText());
                infoCliente.setIpPublicoServidor(jTextFieldIpPublicoServidor.getText());
                infoCliente.setIpLocalServidor(jTextFieldIpLocalServidor.getText());
                try {
                    byte[] ipLocalByteArr = InetAddress.getByName(jTextFieldIpLocalServidor.getText()).getAddress();
                    Socket socket = new Socket(InetAddress.getByAddress(jTextFieldIpPublicoServidor.getText(), ipLocalByteArr), infoCliente.getPortServidor());
                    criaCliente(infoCliente, socket);
                    pcliente = getPosicao();
                    pcliente.y -= 83;
                    cliente.setLocation(pcliente);
                    this.dispose();
                    cliente.setVisible(true);
                } catch (IOException error) {
                    JOptionPane.showMessageDialog(null, "Servidor não encontrado, verifique se os dados estão corretos.", "Servidor não encontrado", JOptionPane.ERROR_MESSAGE);
                }
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Executa o método mudacor em todas as telas
        setCor();
        if(cadCli != null){
            cadCli.mudaCor();
        }
        if(ini != null){
            ini.mudaCor();
        }
        if(cadHost != null){
            cadHost.mudaCor();
        }
        if(info != null){
            info.mudaCor();
        }
        if(serv != null){
            serv.mudaCor();
        }
        if(cliente != null){
            cliente.mudaCor();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastra_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastra_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIpLocalCliente;
    private javax.swing.JTextField jTextFieldIpLocalServidor;
    private javax.swing.JTextField jTextFieldIpPublicoCliente;
    private javax.swing.JTextField jTextFieldIpPublicoServidor;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

//Pega o IP locar através do iNetAddress
private String getIPLocal() {
        try {
            InetAddress iNetAddress = InetAddress.getLocalHost();
            return iNetAddress.getHostAddress();
        } catch (UnknownHostException error) {
            JOptionPane.showMessageDialog(null, error.getCause().toString() + " - " + error.getMessage(), "Erro ao recuperar IP Local", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }
//Confere se o IP inserido é um IP válido
    public static boolean validIP (String ip) {
    try {
        if ( ip == null || ip.isEmpty() ) {
            return false;
        }

        String[] parts = ip.split( "\\." );
        if ( parts.length != 4 ) {
            return false;
        }

        for ( String s : parts ) {
            int i = Integer.parseInt( s );
            if ( (i < 0) || (i > 255) ) {
                return false;
            }
        }
        if ( ip.endsWith(".") ) {
            return false;
        }
       
        return true;
    } catch (NumberFormatException nfe) {
        return false;
    }
}

    
    //Pega o IP público atrvés de sites
    private String getIPPublico() {
        String[] urls = { "http://checkip.amazonaws.com/", "https://myexternalip.com/raw", "https://ipecho.net/plain" };
        String ip = null;
        for (int i = 0, l = urls.length; ip == null && i < l; i++) {
            try {
                URL url = new URL(urls[i]);
                BufferedReader in = new BufferedReader(new InputStreamReader(url.openStream()));
                ip = in.readLine();
            } catch (MalformedURLException error) {
                JOptionPane.showMessageDialog(null, error.getCause().toString() + " - " + error.getMessage(), "Erro ao recuperar IP Público", JOptionPane.ERROR_MESSAGE);
            } catch (IOException error) {
                JOptionPane.showMessageDialog(null, error.getCause().toString() + " - " + error.getMessage(), "Erro ao recuperar IP Público", JOptionPane.ERROR_MESSAGE);
            }
        }
        return ip;
    }
      
    //Faz as verificações necessárias para ver se os IPs inseridos são validos
    private boolean isValidLogin() {
        StringBuilder builder = new StringBuilder();
        if (jTextFieldIpPublicoServidor.getText() == null || jTextFieldIpPublicoServidor.getText().trim().isEmpty())
            builder.append("IP público do servidor não pode ser vazio.\n");
        if (jTextFieldIpLocalServidor.getText() == null || jTextFieldIpLocalServidor.getText().trim().isEmpty())
            builder.append("IP local do servidor não pode ser vazio.\n");
        if (jTextFieldIpPublicoCliente.getText() == null || jTextFieldIpPublicoCliente.getText().trim().isEmpty())
            builder.append("IP público do cliente não pode ser vazio.\n");
        if (jTextFieldIpLocalCliente.getText() == null || jTextFieldIpLocalCliente.getText().trim().isEmpty())
            builder.append("IP local do cliente não pode ser vazio.\n");
        if (jTextFieldNome.getText() == null || jTextFieldNome.getText().trim().isEmpty())
            builder.append("Nome no chat não pode ser vazio.\n");
        if (validIP(jTextFieldIpPublicoCliente.getText()) == false)
            builder.append("IP público do cliente é inválido.\n");
        if (validIP(jTextFieldIpLocalCliente.getText()) == false)
            builder.append("IP local do cliente é inválido.\n");
        
        
        if (!builder.toString().isEmpty())
            JOptionPane.showMessageDialog(null, builder.toString(), "Existem erros de validação.", JOptionPane.ERROR_MESSAGE);
        
        return builder.toString().isEmpty();
    }
   
    }



